// Generated by `npm run codegen` (graphql-code-generator) against the
// composed supergraph -- do not hand-edit. Committed as a placeholder so
// the module type-checks before the backend subgraph exists.
export {};
